version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "tomhanks"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "superhero"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  web:
    build: .
    ports:
      - "5000:5000"
